import { Dish, Review, TeamMember } from './types';

export const dishes: Dish[] = [
  {
    id: 'charred-octopus',
    name: 'Charred Spanish Octopus',
    category: 'Starters',
    description: 'Smoked paprika, fingerling potatoes, salsa verde, and preserved lemon.',
    longDescription: 'Our signature starter features sustainably sourced Spanish octopus, slow-braised for tenderness and finished over open oak coals. Served atop crispy crushed fingerling potatoes with a vibrant salsa verde and a touch of preserved lemon to cut through the richness.',
    price: 1850,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Charred octopus tentacle plated with potatoes and vibrant green salsa verde',
    dietary: ['Gluten-Free', 'Dairy-Free'],
    ingredients: ['Spanish Octopus', 'Fingerling Potatoes', 'Salsa Verde', 'Smoked Paprika', 'Preserved Lemon'],
    isSignature: true,
  },
  {
    id: 'wagyu-tartare',
    name: 'Wagyu Beef Tartare',
    category: 'Starters',
    description: 'Hand-cut wagyu, cured egg yolk, black garlic aioli, house-made sourdough crisps.',
    longDescription: 'Premium A5 Wagyu beef, carefully hand-cut and seasoned with delicate shallots and chives. It is topped with a rich, salt-cured egg yolk and served with a deeply savory black garlic aioli. Accompanied by impossibly thin, crispy sourdough shards.',
    price: 2100,
    image: 'https://images.unsplash.com/photo-1626844131082-256783844137?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Finely diced wagyu beef tartare topped with a cured egg yolk and crispy bread',
    dietary: ['Dairy-Free'],
    ingredients: ['A5 Wagyu Beef', 'Cured Egg Yolk', 'Black Garlic', 'Capers', 'Sourdough'],
  },
  {
    id: 'wood-fired-oysters',
    name: 'Wood-Fired Oysters',
    category: 'Starters',
    description: 'Local half-shell oysters, smoked chili butter, gremolata, grilled lemon.',
    longDescription: 'Freshly shucked local oysters quickly roasted over the open hearth. They are finished with a rich, slightly spicy smoked chili butter and a bright, herbaceous gremolata. Served with a deeply charred half lemon for squeezing.',
    price: 1650,
    image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Roasted oysters on the half shell topped with herb butter on a bed of rock salt',
    dietary: ['Gluten-Free'],
    ingredients: ['Fresh Oysters', 'Smoked Chili Butter', 'Parsley', 'Garlic', 'Lemon'],
  },
  {
    id: 'roasted-beets-burrata',
    name: 'Ember-Roasted Beets & Burrata',
    category: 'Starters',
    description: 'Salt-baked heritage beets, fresh burrata, pistachio dukkah, aged balsamic.',
    longDescription: 'Heritage beets buried in the glowing embers of our hearth until perfectly tender and imbued with a gentle smokiness. Served alongside creamy, fresh Italian burrata, crunchy pistachio dukkah, and drizzled with a 12-year aged balsamic reduction.',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Vibrant roasted beets served with torn burrata cheese and sprinkled with pistachios',
    dietary: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Heritage Beets', 'Burrata Cheese', 'Pistachios', 'Aged Balsamic', 'Olive Oil'],
  },
  {
    id: 'grilled-ribeye',
    name: 'Oak-Grilled Bone-In Ribeye',
    category: 'Mains',
    description: '32oz prime ribeye, charred asparagus, smoked marrow butter, red wine jus.',
    longDescription: 'The centerpiece of the Ember & Oak experience. A 32oz USDA Prime bone-in ribeye, dry-aged for 45 days and grilled over a fierce open oak wood fire. It arrives at your table resting in a pool of rich red wine jus, topped with melting smoked bone marrow butter and served alongside blistered asparagus.',
    price: 6800,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Sliced, perfectly cooked ribeye steak topped with melting butter alongside grilled asparagus',
    dietary: ['Gluten-Free'],
    ingredients: ['32oz Prime Ribeye', 'Bone Marrow', 'Asparagus', 'Red Wine Jus', 'Flaky Sea Salt'],
    isSignature: true,
  },
  {
    id: 'roasted-branzino',
    name: 'Whole Roasted Branzino',
    category: 'Mains',
    description: 'Wood-fired Mediterranean seabass, fennel, citrus, herb salad, burnt orange vinaigrette.',
    longDescription: 'A whole Mediterranean Branzino, stuffed with aromatics and roasted in our wood-fired oven until the skin is impossibly crisp and the flesh is tender and flaky. It is fileted tableside and dressed with a bright burnt orange vinaigrette and a refreshing fennel and herb salad.',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Whole roasted Mediterranean seabass garnished with citrus slices and fresh herbs',
    dietary: ['Gluten-Free', 'Dairy-Free'],
    ingredients: ['Mediterranean Branzino', 'Fennel', 'Citrus', 'Fresh Herbs', 'Olive Oil'],
    isSignature: true,
  },
  {
    id: 'mushroom-risotto',
    name: 'Wild Mushroom Risotto',
    category: 'Mains',
    description: 'Acquerello rice, foraged mushrooms, black truffle shavings, aged parmesan.',
    longDescription: 'A deeply comforting and luxurious vegetarian option. We use aged Acquerello carnaroli rice, slowly cooked with a rich mushroom broth and a medley of seasonal foraged mushrooms. Finished with generous shavings of fresh black truffle and aged Parmigiano-Reggiano.',
    price: 2800,
    image: 'https://images.unsplash.com/photo-1633504581786-316c8002b1b9?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Creamy mushroom risotto in a shallow bowl, topped with shaved black truffle',
    dietary: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Acquerello Rice', 'Wild Mushrooms', 'Black Truffle', 'Parmigiano-Reggiano', 'White Wine'],
  },
  {
    id: 'wood-fired-cauliflower',
    name: 'Wood-Fired Cauliflower Steak',
    category: 'Mains',
    description: 'Harissa marinade, tahini yogurt, pomegranate, toasted almonds.',
    longDescription: 'A thick cut of cauliflower marinated in spicy harissa and roasted in the wood-fired oven until deeply charred and tender. Served over a pool of cooling tahini yogurt and finished with fresh pomegranate seeds, mint, and toasted almonds.',
    price: 1900,
    image: 'https://cookingwithayeh.com/wp-content/uploads/2023/02/Roasted-Cauliflower-Steaks-SQ-3.jpg',
    imageAlt: 'Roasted cauliflower steak on a plate with yogurt and pomegranate seeds',
    dietary: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Cauliflower', 'Harissa', 'Tahini Yogurt', 'Pomegranate', 'Almonds'],
  },
  {
    id: 'smoked-chocolate-tart',
    name: 'Smoked Dark Chocolate Tart',
    category: 'Desserts',
    description: 'Valrhona 70% dark chocolate, toasted marshmallow meringue, graham cracker crust.',
    longDescription: 'A refined take on a campfire classic. A crisp graham cracker tart shell filled with a dense, slightly smoky Valrhona 70% dark chocolate ganache. It is crowned with a towering toasted marshmallow meringue that we torch to order.',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Dark chocolate tart slice with a beautifully torched, towering meringue topping',
    dietary: ['Vegetarian'],
    ingredients: ['Valrhona 70% Chocolate', 'Marshmallow', 'Graham Cracker', 'Smoked Sea Salt'],
    isSignature: true,
  },
  {
    id: 'burnt-honey-panna-cotta',
    name: 'Burnt Honey Panna Cotta',
    category: 'Desserts',
    description: 'Vanilla bean, charred figs, honeycomb candy, micro basil.',
    longDescription: 'Silky smooth vanilla bean panna cotta sweetened with complex, slightly bitter burnt honey. Served with fresh figs that have been quickly charred over the coals, adding a surprising savory note, and finished with crunchy honeycomb candy.',
    price: 1100,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Silky panna cotta in a glass dish topped with fresh figs and honeycomb pieces',
    dietary: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Cream', 'Vanilla Bean', 'Burnt Honey', 'Fresh Figs', 'Honeycomb'],
  },
  {
    id: 'basque-cheesecake',
    name: 'Smoked Vanilla Basque Cheesecake',
    category: 'Desserts',
    description: 'Caramelized top, creamy center, smoked vanilla bean, seasonal fruit compote.',
    longDescription: 'A traditional Basque-style cheesecake baked at high heat in our wood-fired oven to achieve a deeply caramelized, almost burnt exterior that yields to a shockingly creamy, molten center. Infused with smoked vanilla bean and served with a tart seasonal fruit compote.',
    price: 1350,
    image: 'https://assets.bonappetit.com/photos/5c48972f52d8785eddd4a72c/1:1/w_2560%2Cc_limit/burnt-basque-cheesecake-1.jpg',
    imageAlt: 'Slice of Basque cheesecake with a dark caramelized top and creamy center',
    dietary: ['Vegetarian', 'Gluten-Free'],
    ingredients: ['Cream Cheese', 'Smoked Vanilla Bean', 'Eggs', 'Sugar', 'Seasonal Fruit Compote'],
  },
  {
    id: 'charred-lemon-tart',
    name: 'Charred Lemon Tart',
    category: 'Desserts',
    description: 'Meyer lemon curd, torched Swiss meringue, buttery shortbread crust.',
    longDescription: 'A bright, acidic palate cleanser with a complex depth. Our smooth Meyer lemon curd is made with whole charred lemons to temper the sweetness and add a whisper of smoke. It sits in a delicate shortbread crust, piped with dramatic peaks of torched Swiss meringue.',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Lemon tart with golden toasted meringue peaks on a plate',
    dietary: ['Vegetarian'],
    ingredients: ['Meyer Lemon', 'Butter', 'Eggs', 'Shortbread', 'Swiss Meringue'],
  },
  {
    id: 'oak-aged-old-fashioned',
    name: 'Oak-Aged Old Fashioned',
    category: 'Drinks',
    description: 'House-blend bourbon, smoked maple syrup, angostura bitters, orange peel.',
    longDescription: 'Our signature cocktail. We age our proprietary bourbon blend in small, charred oak barrels in-house. Mixed with a touch of smoked maple syrup and classic bitters, served over a large clear ice cube with a flamed orange peel.',
    price: 1400,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Classic Old Fashioned cocktail over a large ice cube, garnished with an orange peel',
    dietary: ['Vegan', 'Gluten-Free'],
    ingredients: ['House Bourbon', 'Smoked Maple Syrup', 'Angostura Bitters', 'Orange Peel'],
    isSignature: true,
  },
  {
    id: 'smoked-rosemary-gimlet',
    name: 'Smoked Rosemary Gimlet',
    category: 'Drinks',
    description: 'Botanical gin, fresh lime juice, smoked rosemary syrup, charred rosemary sprig.',
    longDescription: 'A beautifully balanced, aromatic cocktail that pairs perfectly with our wood-fired menu. We start with a crisp botanical gin and fresh lime juice, sweetening it with a house-made simple syrup infused with heavily smoked rosemary. Garnished with a smoking sprig of fresh rosemary.',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'A green-tinted cocktail in a coupe glass with a sprig of rosemary',
    dietary: ['Vegan', 'Gluten-Free'],
    ingredients: ['Botanical Gin', 'Fresh Lime', 'Smoked Rosemary Syrup', 'Rosemary Sprig'],
  },
  {
    id: 'hearth-spiced-cider',
    name: 'Hearth-Spiced Apple Cider',
    category: 'Drinks',
    description: 'Hot pressed apple cider, toasted cinnamon, star anise, aged rum.',
    longDescription: 'A comforting, warm cocktail for cooler evenings. Freshly pressed local apple cider steeped with whole toasted cinnamon sticks, star anise, and cloves. Fortified with a generous pour of aged dark rum and served steaming hot.',
    price: 1100,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM6Sink1dyu6TagJt82p7NvTDOkbZkM_ASlpybAHjYV3dynPeC4DVYcaQc&s=10',
    imageAlt: 'Two mugs of hot apple cider garnished with cinnamon sticks and star anise',
    dietary: ['Vegan', 'Gluten-Free'],
    ingredients: ['Apple Cider', 'Cinnamon', 'Star Anise', 'Aged Rum'],
  },
  {
    id: 'charred-grapefruit-paloma',
    name: 'Charred Grapefruit Paloma',
    category: 'Drinks',
    description: 'Blanco tequila, charred grapefruit juice, agave, smoked sea salt rim.',
    longDescription: 'A vibrant and refreshing take on the classic Paloma. We use fresh ruby red grapefruits that have been quickly blistered over the coals to extract a deeper, more complex juice. Shaken with premium blanco tequila and agave, served with a smoked sea salt rim.',
    price: 1350,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3tKoVe5ZiDWyRwglXYjCJMQdcdqy-Cg_i6VJy3853gomCyvwpo67xWLY&s=10',
    imageAlt: 'Pink cocktail in a salt-rimmed glass garnished with a slice of grapefruit',
    dietary: ['Vegan', 'Gluten-Free'],
    ingredients: ['Blanco Tequila', 'Charred Grapefruit', 'Agave', 'Smoked Sea Salt'],
  }
];

export const reviews: Review[] = [
  {
    id: 'r1',
    author: 'Sarah Jenkins',
    rating: 5,
    date: 'October 12, 2023',
    content: 'Easily the best dining experience I have had this year. The Oak-Grilled Ribeye was cooked to absolute perfection, and the service was impeccable. The atmosphere strikes the perfect balance between upscale and welcoming.',
    dishId: 'grilled-ribeye'
  },
  {
    id: 'r2',
    author: 'Marcus Thorne',
    rating: 5,
    date: 'November 04, 2023',
    content: 'The Charred Spanish Octopus starter is a revelation. I usually don\'t leave reviews, but the depth of flavor in that one dish compelled me. A must-visit if you appreciate true culinary craftsmanship.',
    dishId: 'charred-octopus'
  },
  {
    id: 'r3',
    author: 'Elena Rodriguez',
    rating: 5,
    date: 'December 18, 2023',
    content: 'We celebrated our anniversary here and it exceeded all expectations. The Smoked Chocolate Tart was the perfect end to an incredible meal. The staff made us feel incredibly special. We will absolutely be returning.',
    dishId: 'smoked-chocolate-tart'
  },
  {
    id: 'r4',
    author: 'David Chen',
    rating: 4.8,
    date: 'January 22, 2024',
    content: 'Incredible attention to detail in every dish. The cocktails are inventive and the food speaks for itself. It\'s definitely on the pricier side, but entirely worth it for the quality of ingredients and execution.'
  },
  {
    id: 'r5',
    author: 'Aisha Patel',
    rating: 5,
    date: 'February 05, 2024',
    content: 'The atmosphere is stunning - moody, warm, and inviting. Ordered the Wild Mushroom Risotto and it was rich and earthy, just perfect for a chilly evening. Can\'t wait to come back and try the rest of the menu.',
    dishId: 'mushroom-risotto'
  }
];

export const team: TeamMember[] = [
  {
    id: 't1',
    name: 'Julian Vance',
    role: 'Executive Chef & Founder',
    bio: 'With over two decades in Michelin-starred kitchens across Europe and the US, Julian returned to his roots to open Ember & Oak. His philosophy centers on elemental cooking - using fire, smoke, and time to elevate pristine, locally sourced ingredients.',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Chef Julian Vance in a white chef coat, standing in a busy kitchen'
  },
  {
    id: 't2',
    name: 'Maya Lin',
    role: 'Head Sommelier',
    bio: 'Maya curates our extensive cellar, focusing on small-production vineyards and natural wines that pair beautifully with our wood-fired menu. Her unpretentious approach to wine makes every pairing an accessible adventure.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Sommelier Maya Lin holding a glass of red wine, smiling warmly'
  },
  {
    id: 't3',
    name: 'Elias Thorne',
    role: 'Bar Director',
    bio: 'Elias brings a scientific precision to our cocktail program. He specializes in barrel-aged spirits, house-made infusions, and incorporating culinary techniques - like smoking and fat-washing - into his deeply layered drinks.',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?q=80&w=1600&auto=format&fit=crop',
    imageAlt: 'Bar Director Elias Thorne mixing a cocktail behind the copper bar'
  }
];
